// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbfdyvzkmdbezivmppbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNiZmR5dnprbWRiZXppdm1wcGJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzNzYxNjAsImV4cCI6MjA3OTk1MjE2MH0.uIL91FreeMngXc4A1oDcS7ggRozIj1ysMRe55XzyJR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});